// constants/schemas.ts

export const expectedSchemas = {
    seizedVehicle: [
        "id",
        "srNo",
        "gdNo",
        "gdDate",
        "underSection",
        "vehicleType",
        "colour",
        "registrationNo",
        "engineNo",
        "description",
        "status",
        "policeStation",
        "ownerName",
        "seizedBy",
        "caseProperty",
        "createdAt",
        "updatedAt"
    ],
    entry: [
        "क्र0सं0",
        "fir No",
        "wine",
        "cash",
        "wine type",
        "photo url",
        "Sr No",
        "Gd no",
        "Gd Date",
        "under section",
        "descrition",
        "year",
        "policestation",
        "विवेचक का नाम",
        "वादी का नाम",
        "एचएम दाखिल कर्ता का नाम",
        "accused",
        "status",
        "entry type",
        "place",
        "box no",
        "court no",
        "court name",
        "case property",
    ],
    movement: [
        "id",
        "srNo",
        "moveDate",
        "firNo",
        "underSection",
        "takenOutBy",
        "moveTrackingNo",
        "movePurpose",
        "name",
        "createdAt",
        "updatedAt"
    ],
    release: [
        "id",
        "srNo",
        "moveDate",
        "firNo",
        "underSection",
        "takenOutBy",
        "moveTrackingNo",
        "movePurpose",
        "name",
        "receiverName",
        "fathersName",
        "address",
        "mobile",
        "releaseItemName",
        "createdAt",
        "updatedAt"
    ]
};
