

export const narora = {
    "Sr. No.": "srNo",
    "Fir No": "firNo",
    "Court No": "courtNo",
    "Court Name": "courtName",
    "GD NO.": "gdNo",
    "GD Date": "gdDate",
    "Under Section": "underSection",
    "एच0एम0/दाखिलकर्ता का नाम": "HM",
    "Description": "description",
    "Case Property": "caseProperty",
    "Police Station": "policeStation",
    "Year": "Year",
    "विवेचक का नाम": "IOName",
    "वादी का नाम": "vadiName",
    "Accused": "accused",
    "Status": "status",
    "Entry Type": "entryType",
    "Place": "place",
    "Box No": "boxNo",
    "WINE": "wine",
    "Wine type": "wineType",
    "Cash": "cash",
};


export const arniya = {

    "SR NO": "srNo",
    "FIR NO": "firNo",
    "UNDER SECTION": "underSection",
    "HM/दाखिल कर्ता का नाम": "HM",
    "DESCRIPTION": "description",
    "CASE PROPERTY": "caseProperty",
    "POLICE STATION": "policeStation",
    "YEAR": "Year",
    "GD N0": "gdNo",
    "GD DATE DD-MM-YY": "gdDate",
    "विवेचक का नाम": "IOName",
    "वादी का नाम": "vadiName",
    "ACCUSED": "accused",
    "STATUS": "status",
    "ENTRY TYPE": "entryType",
    "PLACE": "place",
    "BOX NO": "boxNo",
    "COURT NO": "courtNo",
    "COURT NAME": "courtName",

    "CASH": "cash",
    "WINE": "wine",
    "WINE TYPE": "wineType",
};

export const bhadohi = {
    "FirNo": "firNo",
    "EntryType": "entryType",
    "MudNo": "srNo",
    "PoliceStation": "policeStation",
    "EntryPerson": "HM",
    "IoName": "IOName",
    "GdNo": "gdNo",
    "Description": "description",
    "CaseProperty": "caseProperty",
    "Year": "Year",
    "accused": "accused",
    "Court": "courtName",
    "Location": "place",
    "Under Section": "underSection",
    "Status": "status",

    // missing fields

    "GD DATE": "gdDate",
    "VADI": "vadiName",
    "BOX NO": "boxNo",
    "COURT NO": "courtNo",
    "CASH": "cash",
    "WINE": "wine",
    "WINE TYPE": "wineType",
};

export const sre = {
    "FIR NO": "firNo",
    "EntryType": "entryType",
    "ENTRYTYPE ID": "srNo",
    "POLICESTATION": "policeStation",
    "ENTRY PERSON": "HM",
    "IO NAME": "IOName",
    "GD NO.": "gdNo",
    "DISCRIPTION": "description",
    "CASE PROPERTY": "caseProperty",
    "YEAR": "Year",
    "BANAM": "accused",
    "COURT": "courtName",
    "LOACTION": "place",
    "UNDER SECTION": "underSection",
    "STATUS": "status",

    // missing fields

    "SEIZED DATE": "gdDate",
    "VADI": "vadiName",
    "BOX NO": "boxNo",
    "COURT NO": "courtNo",
    "CASH": "cash",
    "WINE": "wine",
    "WINE TYPE": "wineType",
};



export const mirzapur = {
    "मु0अ0सं0 (FIR No)": "firNo",
    "SrNo": "srNo",
    "दाखिल मालखाना (ENTRY TYPE)": "entryType",
    "case property": "caseProperty",
    "धारा": "underSection",
    "थाना": "policeStation",
    "वर्ष": "Year",
    "जीडी न0": "gdNo",
    "जीडी दिनांक": "gdDate",
    "विवरण": "description",
    "विवेचक का नाम": "IOName",
    "HM/दाखिल कर्ता का नाम": "HM",
    "वादी का नाम": "vadiName",
    "नकद": "cash",
    "शराब (wine)": "wine",
    "शराब का प्रकार (wine type)": "wineType",
    "अभियुक्त Accused": "accused",
    "अभियोग की स्थिति (STATUS)": "status",
    "स्थान": "place",
    "बोक्स न0": "boxNo",
    "court No": "courtNo",
    "कोर्ट का नाम": "courtName",
}

export const sikandrabad = {
    "FIR No.": "firNo",
    "SrNo": "srNo",
    "Entry Type": "entryType",
    "Case Property": "caseProperty",
    "Under Section": "underSection",
    "Police Station": "policeStation",
    "Year": "Year",
    "GD No.": "gdNo",
    "GD Date": "gdDate",
    "Description": "description",
    "ioName": "IOName",
    "hmName": "HM",
    "vadi": "vadiName",
    "cash": "cash",
    "wine": "wine",
    "wine type": "wineType",
    "Accused": "accused",
    "Status": "status",
    "Place": "place",
    "Box No.": "boxNo",
    "Court No.": "courtNo",
    "Court Name": "courtName",
}


export const shamli = {
    "FIR No": "firNo",
    "SR. No": "srNo",
    "Entry Type": "entryType",
    "Case Property": "caseProperty",
    "Under Section": "underSection",
    "Police Station": "policeStation",
    "Year": "Year",
    "GD No.": "gdNo",
    "GD Date": "gdDate",
    "Description": "description",
    "IO Name": "IOName",
    "HM": "HM",
    "Vadi Name": "vadiName",
    "cash": "cash",
    "wine": "wine",
    "wine type": "wineType",
    "Accused": "accused",
    "Status": "status",
    "Place": "place",
    "Box No.": "boxNo",
    "Court No.": "courtNo",
    "Court Name": "courtName",
}

export const baghpat = {
    "firNo": "firNo",
    "srNo": "srNo",
    "entryType": "entryType",
    "caseProperty": "caseProperty",
    "underSection": "underSection",
    "policeStation": "policeStation",
    "Year": "Year",
    "gdNo": "gdNo",
    "gdDate": "gdDate",
    "description": "description",
    "IOName": "IOName",
    "HM": "HM",
    "vadiName": "vadiName",

    "accused": "accused",
    "status": "status",
    "place": "place",
    "boxNo": "boxNo",
    "courtNo": "courtNo",
    "cash": "cash",
    "wine": "wine",
    "wineType": "wineType",
    "courtName": "courtName",
}

export const mau = {
    "मु0अ0सं0 (FIR No)": "firNo",
    "क्र0सं0(Sr No)": "srNo",
    "दाखिल मालखाना (ENTRY TYPE)": "entryType",
    "case property": "caseProperty",
    "धारा": "underSection",
    "थाना": "policeStation",
    "वर्ष": "Year",
    "जीडी न0": "gdNo",
    "जीडी दिनांक": "gdDate",
    "विवरण": "description",
    "विवेचक का नाम": "IOName",
    "HM/दाखिल कर्ता का नाम": "HM",
    "वादी का नाम": "vadiName",
    "अभियुक्त Accused": "accused",
    "अभियोग की स्थिति (STATUS)": "status",
    "स्थान": "place",
    "बोक्स न0": "boxNo",
    "कोर्ट सं0": "courtNo",
    "कोर्ट का नाम": "courtName",
    "नकद (case)": "cash",
    "शराब (wine)": "wine",
    "शराब का प्रकार (wine type)": "wineType",
}

export const ballia = {
    "मु0अ0सं0 (FIR No)": "firNo",
    "क्र0सं0(Sr No)": "srNo",
    "दाखिल मालखाना (ENTRY TYPE)": "entryType",
    "case property": "caseProperty",
    "धारा": "underSection",
    "थाना": "policeStation",
    "वर्ष": "Year",
    "जीडी न0": "gdNo",
    "जीडी दिनांक": "gdDate",
    "विवरण": "description",
    "विवेचक का नाम": "IOName",
    "HM/दाखिल कर्ता का नाम": "HM",
    "वादी का नाम": "vadiName",
    "अभियुक्त Accused": "accused",
    "अभियोग की स्थिति (STATUS)": "status",
    "स्थान": "place",
    "बोक्स न0": "boxNo",
    "कोर्ट सं0": "courtNo",
    "कोर्ट का नाम": "courtName",
    "नकद (case)": "cash",
    "शराब (wine)": "wine",
    "शराब का प्रकार (wine type)": "wineType",
}