

export const narora = {
    "Sr. No.": "srNo",
    "Fir NO": "firNo",
    "Court No": "courtNo",
    "Court Name": "courtName",
    "GD NO.": "gdNo",
    "GD Date": "gdDate",
    "Under Section": "underSection",
    "एच0एम0/दाखिलकर्ता का नाम": "HM",
    "Description": "description",
    "Case Property": "caseProperty",
    "Police Station": "policeStation",
    "Year": "Year",
    "विवेचक का नाम": "IOName",
    "वादी का नाम": "vadiName",
    "Accused": "accused",
    "Status": "status",
    "Entry Type": "entryType",
    "Place": "place",
    "Box No": "boxNo",
    "WINE": "wine",
    "Wine type": "wineType",
    "Cash": "cash",
};


export const arniya = {
    "CASH": "cash",
    "WINE": "wine",
    "WINE TYPE": "wineType",
    "SR NO": "srNo",
    "FIR NO": "firNo",
    "GD N0": "gdNo",
    "GD DATE DD-MM-YY": "gdDate",
    "UNDER SECTION": "underSection",
    "HM/दाखिल कर्ता का नाम": "HM",
    "DESCRIPTION": "description",
    "CASE PROPERTY": "caseProperty",
    "POLICE STATION": "policeStation",
    "YEAR": "Year",
    "विवेचक का नाम": "IOName",
    "वादी का नाम": "vadiName",
    "ACCUSED": "accused",
    "STATUS": "status",
    "ENTRY TYPE": "entryType",
    "PLACE": "place",
    "BOX NO": "boxNo",
    "COURT NO": "courtNo",
    "COURT NAME": "courtName",
};



export const mirzapur = {
    "मु0अ0सं0 (FIR No)": "firNo",
    "SR No": "srNo",
    "दाखिल मालखाना (ENTRY TYPE)": "entryType",
    "case property": "caseProperty",
    "धारा": "underSection",
    "थाना": "policeStation",
    "वर्ष": "Year",
    "जीडी न0": "gdNo",
    "जीडी दिनांक": "gdDate",
    "विवरण": "description",
    "विवेचक का नाम": "IOName",
    "HM/दाखिल कर्ता का नाम": "HM",
    "वादी का नाम": "vadiName",
    "नकद (case)": "cash",
    "शराब (wine)": "wine",
    "शराब का प्रकार (wine type)": "wineType",
    "अभियुक्त Accused": "accused",
    "अभियोग की स्थिति (STATUS)": "status",
    "स्थान": "place",
    "बोक्स न0": "boxNo",
    "court No": "courtNo",
    "कोर्ट का नाम": "courtName",
}